name: Tests

# Controls when the workflow will run
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master", "develop"]

# Jobs to be run. In this case, there is only one named 'build'
jobs:
  build:
    # Defining a matrix-combination strategy to run multiple systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This matrix will create a total of 8 systems:
        #   - Ubuntu: python 3.8, 3.9, 3.10 and 3.11
        #   - Windows: python 3.8, 3.9, 3.10 and 3.11
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    # Steps to be run by each system.
    # Each step is separated by "-", consider using good names
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # It is important to install the current directory (".")
      #  to run the test on the latest code of our package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest .
      - name: Run unittests
        run: pytest unittests
